import { Location, Report, Route3DHighlight, SceneRoad } from '../types';

export type TripRoadCharacter = 'motorway' | 'highway' | 'arterial' | 'city' | 'suburban' | 'rural' | 'mountain' | 'scenic' | 'tunnel' | 'bridge' | 'ramp' | 'unknown';
export interface TripIntelligenceSample { location: Location; distanceFromStartMeters: number; road: SceneRoad | null; trafficPressure: number; roadQuality: number; elevationMeters: number | null; buildingDensity: number; treeDensity: number; characters: TripRoadCharacter[]; }
export interface TripChapter { startMeters: number; endMeters: number; title: string; characters: TripRoadCharacter[]; roadQuality: number; trafficPressure: number; difficulty: number; elevationGainMeters: number; }
export interface TripTrafficForecast { hourOffset: number; pressure: number; confidence: number; basis: 'historical'|'live'|'mixed'|'unknown'; }
export interface TripWeatherSummary { score: number; label: 'low'|'moderate'|'high'; precipitationProbability: number; windKph: number; temperatureC: number | null; coverage: number; }
export interface TripIntelligenceSummary { distanceMeters: number; durationSeconds: number | null; roadQuality: number; roadQualityConfidence: number; trafficPressure: number; trafficForecast: TripTrafficForecast[]; recommendedDepartureOffsetHours: number | null; tollRoadsSampled: number; incidentCounts: { construction: number; closures: number; accidents: number; trafficJams: number }; difficulty: number; elevationGainMeters: number; elevationLossMeters: number; maxGradePercent: number; characters: Array<{ character: TripRoadCharacter; percent: number }>; chapters: TripChapter[]; warnings: string[]; dataCoverage: number; confidence: number; weatherRisk?: TripWeatherSummary; }

const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,Number.isFinite(n)?n:min));
const rad=(n:number)=>n*Math.PI/180;
export function distanceMeters(a:Location,b:Location){const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng);const h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
export function routePolyline(route:Route3DHighlight):Location[]{return route.segments.flatMap(s=>s.coords.map(c=>({lat:c.lat,lng:c.lng})));}
export function sampleRoute(route:Route3DHighlight, stepMeters=30000):Location[]{const pts=routePolyline(route);if(!pts.length)return[];const out=[pts[0]];let carry=0,total=0;for(let i=1;i<pts.length;i++){const d=distanceMeters(pts[i-1],pts[i]);total+=d;carry+=d;if(carry>=stepMeters){out.push(pts[i]);carry=0;}}if(distanceMeters(out[out.length-1],pts[pts.length-1])>1000)out.push(pts[pts.length-1]);return out;}
function roadKind(road:SceneRoad|null):TripRoadCharacter{if(!road?.highway)return'unknown';const h=road.highway.toLowerCase();if(road.tunnel)return'tunnel';if(road.bridge)return'bridge';if(['motorway_link','trunk_link','primary_link','secondary_link'].includes(h))return'ramp';if(h==='motorway')return'motorway';if(['trunk','primary'].includes(h))return'highway';if(['secondary','tertiary'].includes(h))return'arterial';if(['residential','living_street','unclassified'].includes(h))return'city';if(['service'].includes(h))return'suburban';return'rural';}
export function classifyRoadCharacter(sample:Pick<TripIntelligenceSample,'road'|'elevationMeters'|'buildingDensity'|'treeDensity'>, nextElevationMeters:number|null, nextDistanceMeters:number):TripRoadCharacter[]{const base=roadKind(sample.road);const out:TripRoadCharacter[]=[];if(base!=='unknown')out.push(base);if(sample.elevationMeters!=null&&nextElevationMeters!=null&&nextDistanceMeters>100){const grade=Math.abs(nextElevationMeters-sample.elevationMeters)/nextDistanceMeters;if(grade>=0.045)out.push('mountain');}if(sample.treeDensity>=0.42&&sample.buildingDensity<=0.22&&['rural','arterial','highway'].includes(base))out.push('scenic');if(sample.buildingDensity>=0.55&&['city','arterial','suburban'].includes(base))out.push('city');return[...new Set(out)];}
export function scoreRoadQuality(road:SceneRoad|null):number{if(!road)return 55;let s=72;const surface=(road.surface||'').toLowerCase();const smooth=(road.smoothness||'').toLowerCase();if(['asphalt','concrete','paved'].some(x=>surface.includes(x)))s+=10;if(['gravel','ground','dirt','unpaved'].some(x=>surface.includes(x)))s-=22;if(['excellent','good'].includes(smooth))s+=8;if(['intermediate'].includes(smooth))s-=3;if(['bad','very_bad','horrible','very_horrible'].includes(smooth))s-=25;if(road.maxspeed)s+=3;return clamp(s);}
export function summarizeTrip(samples:TripIntelligenceSample[], route:Route3DHighlight, reports:Report[]=[]):TripIntelligenceSummary{const distance=route.distance_meters??0;const chars=new Map<TripRoadCharacter,number>();let q=0,t=0,d=0,w=0,gain=0,loss=0,maxGrade=0;for(let i=0;i<samples.length;i++){const s=samples[i],next=samples[i+1];const span=next?Math.max(1,next.distanceFromStartMeters-s.distanceFromStartMeters):Math.max(1,distance-s.distanceFromStartMeters);for(const c of s.characters)chars.set(c,(chars.get(c)||0)+span);q+=s.roadQuality*span;t+=s.trafficPressure*span;d+=(100-s.roadQuality)*0.35+s.trafficPressure*0.45+(s.characters.includes('mountain')?22:0)+(s.characters.includes('city')?6:0);w+=span;if(next?.elevationMeters!=null&&s.elevationMeters!=null){const delta=next.elevationMeters-s.elevationMeters;if(delta>0)gain+=delta;else loss-=delta;maxGrade=Math.max(maxGrade,Math.abs(delta)/Math.max(1,span)*100);}}for(const r of reports){const near=samples.some(s=>distanceMeters(s.location,r.location)<2500);if(near)t=Math.min(100,t+8);}const chapters:TripChapter[]=[];for(let i=0;i<samples.length;i+=Math.max(1,Math.ceil(samples.length/8))){const group=samples.slice(i,i+Math.max(1,Math.ceil(samples.length/8)));if(!group.length)continue;const start=group[0].distanceFromStartMeters,end=(group[group.length-1]?.distanceFromStartMeters??start)+Math.max(1000,distance/(samples.length||1));const c=[...new Set(group.flatMap(x=>x.characters))];chapters.push({startMeters:start,endMeters:Math.min(distance,end),title:c.includes('mountain')?'Mountain section':c.includes('city')?'City driving':c.includes('scenic')?'Scenic stretch':c.includes('motorway')?'Motorway':c.includes('highway')?'Highway':'Rural road',characters:c,roadQuality:Math.round(group.reduce((a,x)=>a+x.roadQuality,0)/group.length),trafficPressure:Math.round(group.reduce((a,x)=>a+x.trafficPressure,0)/group.length),difficulty:Math.round(group.reduce((a,x)=>a+(100-x.roadQuality)*.35+x.trafficPressure*.45+(x.characters.includes('mountain')?22:0),0)/group.length),elevationGainMeters:Math.round(group.reduce((a,x,j)=>{const prev=j>0?group[j-1]:null;return a+(prev?.elevationMeters!=null&&x.elevationMeters!=null&&x.elevationMeters>prev.elevationMeters?x.elevationMeters-prev.elevationMeters:0);},0))});}
const total=[...chars.values()].reduce((a,b)=>a+b,0)||1;return{distanceMeters:distance,durationSeconds:route.duration_seconds,roadQuality:Math.round(q/(w||1)),trafficPressure:Math.round(t/(w||1)),difficulty:Math.round(clamp(d/(samples.length||1))),elevationGainMeters:Math.round(gain),elevationLossMeters:Math.round(loss),maxGradePercent:Math.round(maxGrade*10)/10,characters:[...chars.entries()].map(([character,n])=>({character,percent:Math.round(n/total*100)})).sort((a,b)=>b.percent-a.percent),chapters,warnings:[...(samples.filter(s=>s.trafficPressure>=75).length?['Heavy reported traffic on parts of the route.']:[]),...(samples.some(s=>s.roadQuality<45)?['Some sampled roads have lower-quality surface data.']:[]),...(samples.some(s=>s.elevationMeters==null)?['Elevation coverage is incomplete.']:[])],dataCoverage:Math.round(samples.filter(s=>s.road||s.elevationMeters!=null).length/(samples.length||1)*100),roadQualityConfidence:Math.round(samples.filter(s=>s.road?.surface||s.road?.smoothness).length/(samples.length||1)*100),trafficForecast:[],recommendedDepartureOffsetHours:null,tollRoadsSampled:samples.filter(s=>s.road?.toll).length,incidentCounts:{construction:reports.filter(r=>r.type==='construction').length,closures:reports.filter(r=>r.type==='closed_lane').length,accidents:reports.filter(r=>r.type==='accident').length,trafficJams:reports.filter(r=>r.type==='traffic_jam').length},confidence:Math.round(samples.length?Math.min(100,55+samples.filter(s=>s.road&&s.elevationMeters!=null).length/samples.length*45):0)};}
